
package cs321.create;
import cs321.common.ParseArgumentException;

/**
 * SSHCreateBTreeArguments
 *
 * @author Diego Dominguez
 *
 */
public class SSHCreateBTreeArguments
{
	/* TODO: Complete this class */

    private final boolean useCache;
    private final int degree;
    private final String SSHFileName;
    private final String treeType;
    private final int cacheSize;
    private final int debugLevel;
    private final int useDatabase;


    private final int degreeForFile;
    /**
     *   "<btree-file> is the name of the BTree file generated by the SSHCreateBTree
     * program. The name that should be used by SSHCReateBTree program should be of
     * the form SSH_log.txt.ssh.btree.<type>.<degree>  "
     *
     *
     * With this being said, the file names have to match up. but in some instances
     * --degree=0 as for the script. If this is the case, then have degreeForFile be 0 so
     * that it gets named correctly but make the real degree 128 (default)
     */


    /**
     * Builds a new SSHCreateBTreeArguments with the specified
     * command line arguments and tests their validity.
     *
     * @param useCache boolean for using cache or not
     * @param degree degree for BTree
     * @param SSHFileName String of filename
     * @param treeType type of tree
     * @param cacheSize size of cache if using
     * @param debugLevel level of debugging
     */
    private SSHCreateBTreeArguments(boolean useCache, int degree, String SSHFileName, String treeType, int cacheSize,int useDatabase, int debugLevel, int degreeForFile)
    {
        this.useCache = useCache;
        this.degree = degree;
        this.SSHFileName = SSHFileName;
        this.treeType = treeType;
        this.cacheSize = cacheSize;
        this.debugLevel = debugLevel;
        this.useDatabase = useDatabase;
        this.degreeForFile = degreeForFile;
    }

    public static SSHCreateBTreeArguments parse(String[] args) throws ParseArgumentException {
        if (args == null || args.length == 0) {
            throw new ParseArgumentException("No arguments provided.");
        }

        boolean useCache = false;
        Integer degree = 128; //(4096 - Integer.BYTES - 1 + (2 * Long.BYTES)) / (4 * Long.BYTES);
        String SSHFileName = null;
        String treeType = "btree";
        int cacheSize = 0;
        int debugLevel = 0;
        int useDatabase = 0;
        int degreeForFile = 0;

        for (String arg : args) {
            if (arg.startsWith("--degree=") ) {
//                String userValue = arg.substring("--degree=".length());
//                try {
//                    degree = Integer.parseInt(userValue);
                    /*
                    for some reason, the script somethimes runs --degree=0, if this is the case
                    I plan on grabbing it and making it 128 (the default degree)
                     */

//                    if (degree <= 1){
//                        degree = 128;
//                    }
//
//                    if (degree <= 0) throw new NumberFormatException();
//                } catch (NumberFormatException e) {
//                    throw new ParseArgumentException("degree must be a positive: " + userValue);
//                }
                String userValue = arg.substring("--degree=".length());
                try{
                    degreeForFile = Integer.parseInt(userValue);

                    //right off the bat, if it is negative, throw
                    if (degreeForFile < 0){
                        throw new NumberFormatException();
                    }

                    // these are not valid degrees, so use the default
                    if (degreeForFile < 1){
                        degree = 128;
                    }

                    //valid degree, just copy over
                    else {
                        degree = degreeForFile;
                    }


                } catch (NumberFormatException e){
                    throw new ParseArgumentException("degree must be a positive: " + userValue);
                }



            }
            else if (arg.startsWith("--ssh-File=") || arg.startsWith("--sshFile=")) {
                String key = arg.substring(0, arg.indexOf('=') + 1);
                SSHFileName = arg.substring(key.length()).trim();
                if (SSHFileName.isEmpty()) {
                    throw new ParseArgumentException(key + " is empty");
                }
            }
            else if ( arg.startsWith("--type")) {
                //treeType = arg.substring("--tree-type=".length()).trim();
                treeType = arg.substring("--type=".length()).trim().toLowerCase();
                if (treeType.isEmpty()) {
                    throw new ParseArgumentException("tree type is empty");
                }
            }
            else if (arg.startsWith("--cache=")) {
                String userValue = arg.substring("--cache=".length());
                if (!"0".equals(userValue) && !"1".equals(userValue)) {
                    throw new ParseArgumentException("cache must be 0 or 1 " + userValue);
                }
                useCache = "1".equals(userValue);
            }
            else if (arg.startsWith("--cache-size=")) {
                String userValue = arg.substring("--cache-size=".length());
                int i;
                try {
                    i = Integer.parseInt(userValue);
                } catch (NumberFormatException e) {
                    throw new ParseArgumentException("Invalid integer  " + userValue);
                }
                if (i <= 0) {
                    throw new ParseArgumentException("cache size must be greater than 0");
                }
                cacheSize = i;
                useCache = true;
            }
            else if(arg.startsWith("--database=")) {
                String userValue = arg.substring("--database=".length());
                if (!"yes".equals(userValue) && !"no".equals(userValue)) {
                    throw new ParseArgumentException("database must be yes or no " + userValue);
                }
                //useDatabase = Integer.parseInt(userValue);
                /*
                To keep changes minimal, useDatabase will still be an int,
                 */
                if ("yes".equals(userValue)) {
                    useDatabase = 1;
                }
                else if ("no".equals(userValue)) {
                    useDatabase = 0;
                }
                else {
                    //should never reach here, but just in case it returns -1
                    useDatabase = -1;
                }

            }
            else if (arg.startsWith("--debug=")) {
                String userValue = arg.substring("--debug=".length());
                if (!"0".equals(userValue) && !"1".equals(userValue)) {
                    throw new ParseArgumentException("debug must be 0 or 1: " + userValue);
                }
                debugLevel = Integer.parseInt(userValue);
            }
            else {
                throw new ParseArgumentException("Unknown argument: " + arg);
            }
        }

        if (degree == null) {
            throw new ParseArgumentException("Missing required degree");
        }
        if (SSHFileName == null) {
            throw new ParseArgumentException("Missing required file");
        }
        if (useCache && cacheSize <= 0) {
            throw new ParseArgumentException("cache size must be provided");
        }

        return new SSHCreateBTreeArguments(useCache, degree, SSHFileName, treeType, cacheSize,useDatabase, debugLevel, degreeForFile);
    }


    public boolean useCache() { return useCache; }
    public int getDegree() { return degree; }
    public String getSSHFileName() { return SSHFileName; }
    public String getTreeType() { return treeType; }
    public int getCacheSize() { return cacheSize; }
    public int getDebugLevel() { return debugLevel; }
    public int getDebug() { return debugLevel; }
    public int getUseDatabase() { return useDatabase; }

    public int getDegreeForFile() { return degreeForFile; }

    @Override
    public String toString()
    {
        return "SSHFileNameCreateBTreeArguments{" +
                "useCache=" + useCache +
                ", degree=" + degree +
                ", SSH_Log_File='" + SSHFileName + '\'' +
                ", TreeType=" + treeType +
                ", cacheSize=" + cacheSize +
                ", debugLevel=" + debugLevel +
                '}';
    }
}
